name: album
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  lottie: ^3.3.1
  leak_tracker: 10.0.9
  leak_tracker_flutter_testing: 3.0.9
  leak_tracker_testing: 3.0.1
  lints: ^5.0.0
  material_color_utilities: 0.11.1  
  meta: 1.16.0                    
  test_api: 0.7.4                 
  vector_math: 2.1.4             
  vm_service: 15.0.0              
  cupertino_icons: ^1.0.8
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Bentham
      fonts:
        - asset: assets/fonts/Bentham-Regular.ttf
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
